theme: jekyll-theme-cayman
show_downloads: true
defaults:
  - scope:
      path: "assets/gifs"
    values:
      gif: true
  - scope:
      path: "assets/wavs"
    values:
      wav: true
baseurl: /ESRelation